export enum ActionTypes {
  SET_ALL = 'SET_ALL',
  SET_FIRSTNAME = 'SET_FIRSTNAME',
  SET_LASTNAME = 'SET_LASTNAME',
  SET_PATRONYMIC = 'SET_PATRONYMIC',
  SET_QUESTION = 'SET_QUESTION',
  SET_ANSWER = 'SET_ANSWER',
}
